CREATE TABLE `parcel_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned DEFAULT NULL,
  `total_price` double DEFAULT '0' COMMENT 'Сумма с учётом всех налогов и скидок',
  `currency_id` bigint unsigned DEFAULT NULL,
  `rate` double(8,2) DEFAULT '1.00',
  `note` varchar(191) DEFAULT NULL,
  `tax` double DEFAULT '1',
  `status` varchar(255) DEFAULT 'new',
  `address_from` longtext,
  `phone_from` varchar(255) DEFAULT NULL,
  `username_from` varchar(255) DEFAULT NULL,
  `address_to` longtext,
  `phone_to` varchar(255) DEFAULT NULL,
  `username_to` varchar(255) DEFAULT NULL,
  `delivery_fee` double DEFAULT '0',
  `km` double DEFAULT '0',
  `deliveryman_id` bigint unsigned DEFAULT NULL,
  `delivery_date` date DEFAULT NULL,
  `delivery_time` varchar(255) DEFAULT NULL,
  `current` tinyint(1) DEFAULT '0',
  `img` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `type_id` bigint unsigned DEFAULT NULL,
  `qr_value` varchar(255) DEFAULT NULL,
  `notify` tinyint(1) NOT NULL DEFAULT '0',
  `instruction` varchar(255) DEFAULT NULL,
  `description` text,
  PRIMARY KEY (`id`),
  KEY `parcel_orders_currency_id_foreign` (`currency_id`),
  KEY `parcel_orders_deliveryman_id_foreign` (`deliveryman_id`),
  KEY `parcel_orders_type_id_foreign` (`type_id`),
  CONSTRAINT `parcel_orders_currency_id_foreign` FOREIGN KEY (`currency_id`) REFERENCES `currencies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `parcel_orders_deliveryman_id_foreign` FOREIGN KEY (`deliveryman_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `parcel_orders_type_id_foreign` FOREIGN KEY (`type_id`) REFERENCES `parcel_order_settings` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;

INSERT INTO `parcel_orders` VALUES (1,702,32.55,3,1.00,NULL,0,'accepted','{\"address\":\"Musina, Messina-Nancefield, Amarula Street, 4020\",\"latitude\":-22.342822625824205,\"longitude\":30.016422048211098}','4555','Sdd','{\"address\":\"Musina, Messina-Nancefield, Botania Crescent, 4118\",\"latitude\":-22.34428817699057,\"longitude\":30.016930662095547}','088855268','fgfh',32.55,0.17,NULL,'2024-08-01','3 : 52',0,NULL,'2024-07-31 23:52:34','2024-07-31 23:52:34',3,NULL,0,NULL,NULL);
